version: '3'
services:
  flask-app:
    build: .
    container_name: to_do_app
    environment:
      - FLASK_DEBUG=true
      - PYTHONUNBUFFERED=True
      - DATABASE_URL=postgresql://postgres:mypassword@db:5432/to_do_list
    restart: on-failure
    expose:
      - 5000
    ports:
      - "5000:5000"
    command: flask run -h 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./pg_db:/var/lib/postgresql@14/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=to_do_list
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=myemail@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mypassword
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
    expose:
      - 5555
    ports:
      - "5555:5555"
